In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline
spi_matches=pd.read_csv('Data/spi_matches.csv')
spi_global_teams=pd.read_csv('Data/spi_global_rankings.csv')
spi_global_nations=pd.read_csv('Data/spi_global_rankings_intl.csv')

In [2]:
spi_matches

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,importance1,importance2,score1,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2
0,2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.8380,0.1157,...,32.4,67.7,0.0,1.0,0.97,0.63,0.43,0.45,0.00,1.05
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,53.7,22.9,2.0,2.0,2.45,0.77,1.75,0.42,2.10,2.10
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,38.1,22.2,2.0,1.0,0.85,2.77,0.17,1.25,2.10,1.05
3,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,43.6,34.6,0.0,1.0,1.11,0.68,0.84,1.60,0.00,1.05
4,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,31.9,48.0,1.0,1.0,0.73,1.11,0.88,1.81,1.05,1.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32246,2020-05-24,1869,Spanish Primera Division,Villarreal,Eibar,73.84,73.46,0.4872,0.2588,0.2540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32247,2020-05-24,1871,Spanish Segunda Division,Las Palmas,Extremadura UD,36.80,31.54,0.4904,0.2091,0.3004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32248,2020-05-24,1871,Spanish Segunda Division,Numancia,Tenerife,29.52,30.98,0.4367,0.2657,0.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32249,2020-05-24,1871,Spanish Segunda Division,Elche,Real Oviedo,32.18,30.04,0.4768,0.2473,0.2759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32250,2020-05-24,1871,Spanish Segunda Division,Real Zaragoza,SD Ponferradina,37.74,29.92,0.5405,0.2037,0.2558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
spi_global_teams[spi_global_teams['name']=='Villarreal']

    rank  prev_rank        name                    league   off   def    spi
31    32       31.0  Villarreal  Spanish Primera Division  2.14  0.83  73.84

In [4]:
df_left = pd.merge(spi_matches, spi_global_teams[['name','off']], left_on='team1', right_on="name",how='left')

In [5]:
df_left

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,score1,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2,name,off
0,2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.8380,0.1157,...,0.0,1.0,0.97,0.63,0.43,0.45,0.00,1.05,NaN,NaN
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,2.0,2.0,2.45,0.77,1.75,0.42,2.10,2.10,AS Monaco,1.85
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,2.0,1.0,0.85,2.77,0.17,1.25,2.10,1.05,Hull City,1.34
3,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,0.0,1.0,1.11,0.68,0.84,1.60,0.00,1.05,Crystal Palace,1.90
4,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,1.0,1.0,0.73,1.11,0.88,1.81,1.05,1.05,Everton,1.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32246,2020-05-24,1869,Spanish Primera Division,Villarreal,Eibar,73.84,73.46,0.4872,0.2588,0.2540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Villarreal,2.14
32247,2020-05-24,1871,Spanish Segunda Division,Las Palmas,Extremadura UD,36.80,31.54,0.4904,0.2091,0.3004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Las Palmas,1.02
32248,2020-05-24,1871,Spanish Segunda Division,Numancia,Tenerife,29.52,30.98,0.4367,0.2657,0.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Numancia,0.76
32249,2020-05-24,1871,Spanish Segunda Division,Elche,Real Oviedo,32.18,30.04,0.4768,0.2473,0.2759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Elche,0.92
32250,2020-05-24,1871,Spanish Segunda Division,Real Zaragoza,SD Ponferradina,37.74,29.92,0.5405,0.2037,0.2558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Real Zaragoza,1.08

In [6]:
df_left.rename(columns={"off": "off_team1"})
del df_left['name']

In [7]:
df_all = pd.merge(df_left, spi_global_teams[['name','off']], left_on='team2', right_on="name",how='left')

In [8]:
df_all

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2,off_x,name,off_y
0,2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.8380,0.1157,...,1.0,0.97,0.63,0.43,0.45,0.00,1.05,NaN,Paris Saint-Germain,2.75
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,2.0,2.45,0.77,1.75,0.42,2.10,2.10,1.85,Guingamp,1.35
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,1.0,0.85,2.77,0.17,1.25,2.10,1.05,1.34,Leicester City,2.01
3,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,1.0,1.11,0.68,0.84,1.60,0.00,1.05,1.90,West Bromwich Albion,1.66
4,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,1.0,0.73,1.11,0.88,1.81,1.05,1.05,1.98,Tottenham Hotspur,2.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32246,2020-05-24,1869,Spanish Primera Division,Villarreal,Eibar,73.84,73.46,0.4872,0.2588,0.2540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.14,Eibar,1.87
32247,2020-05-24,1871,Spanish Segunda Division,Las Palmas,Extremadura UD,36.80,31.54,0.4904,0.2091,0.3004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02,Extremadura UD,0.77
32248,2020-05-24,1871,Spanish Segunda Division,Numancia,Tenerife,29.52,30.98,0.4367,0.2657,0.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.76,Tenerife,0.94
32249,2020-05-24,1871,Spanish Segunda Division,Elche,Real Oviedo,32.18,30.04,0.4768,0.2473,0.2759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.92,Real Oviedo,0.92
32250,2020-05-24,1871,Spanish Segunda Division,Real Zaragoza,SD Ponferradina,37.74,29.92,0.5405,0.2037,0.2558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.08,SD Ponferradina,0.92

In [9]:
spi_global_teams[spi_global_teams['name']=='Paris Saint-Germain']

   rank  prev_rank                 name          league   off   def    spi
3     4        4.0  Paris Saint-Germain  French Ligue 1  2.75  0.41  89.51

In [10]:
df_all

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2,off_x,name,off_y
0,2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.8380,0.1157,...,1.0,0.97,0.63,0.43,0.45,0.00,1.05,NaN,Paris Saint-Germain,2.75
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,2.0,2.45,0.77,1.75,0.42,2.10,2.10,1.85,Guingamp,1.35
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,1.0,0.85,2.77,0.17,1.25,2.10,1.05,1.34,Leicester City,2.01
3,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,1.0,1.11,0.68,0.84,1.60,0.00,1.05,1.90,West Bromwich Albion,1.66
4,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,1.0,0.73,1.11,0.88,1.81,1.05,1.05,1.98,Tottenham Hotspur,2.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32246,2020-05-24,1869,Spanish Primera Division,Villarreal,Eibar,73.84,73.46,0.4872,0.2588,0.2540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.14,Eibar,1.87
32247,2020-05-24,1871,Spanish Segunda Division,Las Palmas,Extremadura UD,36.80,31.54,0.4904,0.2091,0.3004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02,Extremadura UD,0.77
32248,2020-05-24,1871,Spanish Segunda Division,Numancia,Tenerife,29.52,30.98,0.4367,0.2657,0.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.76,Tenerife,0.94
32249,2020-05-24,1871,Spanish Segunda Division,Elche,Real Oviedo,32.18,30.04,0.4768,0.2473,0.2759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.92,Real Oviedo,0.92
32250,2020-05-24,1871,Spanish Segunda Division,Real Zaragoza,SD Ponferradina,37.74,29.92,0.5405,0.2037,0.2558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.08,SD Ponferradina,0.92

In [11]:
df_all = df_all[np.isfinite(df_all['off_x'])]

In [12]:
df_all

,date,league_id,league,team1,team2,spi1,spi2,prob1,prob2,probtie,...,score2,xg1,xg2,nsxg1,nsxg2,adj_score1,adj_score2,off_x,name,off_y
1,2016-08-12,1843,French Ligue 1,AS Monaco,Guingamp,68.85,56.48,0.5714,0.1669,0.2617,...,2.0,2.45,0.77,1.75,0.42,2.10,2.10,1.85,Guingamp,1.35
2,2016-08-13,2411,Barclays Premier League,Hull City,Leicester City,53.57,66.81,0.3459,0.3621,0.2921,...,1.0,0.85,2.77,0.17,1.25,2.10,1.05,1.34,Leicester City,2.01
3,2016-08-13,2411,Barclays Premier League,Crystal Palace,West Bromwich Albion,55.19,58.66,0.4214,0.2939,0.2847,...,1.0,1.11,0.68,0.84,1.60,0.00,1.05,1.90,West Bromwich Albion,1.66
4,2016-08-13,2411,Barclays Premier League,Everton,Tottenham Hotspur,68.02,73.25,0.3910,0.3401,0.2689,...,1.0,0.73,1.11,0.88,1.81,1.05,1.05,1.98,Tottenham Hotspur,2.33
5,2016-08-13,2411,Barclays Premier League,Middlesbrough,Stoke City,56.32,60.35,0.4380,0.2692,0.2927,...,1.0,1.40,0.55,1.13,1.06,1.05,1.05,1.25,Stoke City,1.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32246,2020-05-24,1869,Spanish Primera Division,Villarreal,Eibar,73.84,73.46,0.4872,0.2588,0.2540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.14,Eibar,1.87
32247,2020-05-24,1871,Spanish Segunda Division,Las Palmas,Extremadura UD,36.80,31.54,0.4904,0.2091,0.3004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02,Extremadura UD,0.77
32248,2020-05-24,1871,Spanish Segunda Division,Numancia,Tenerife,29.52,30.98,0.4367,0.2657,0.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.76,Tenerife,0.94
32249,2020-05-24,1871,Spanish Segunda Division,Elche,Real Oviedo,32.18,30.04,0.4768,0.2473,0.2759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.92,Real Oviedo,0.92
32250,2020-05-24,1871,Spanish Segunda Division,Real Zaragoza,SD Ponferradina,37.74,29.92,0.5405,0.2037,0.2558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.08,SD Ponferradina,0.92