## Data Transformation
Text data requires preparation before it can be used in predictive modeling. We need to perform tokenization and vectorization of the text data.

#### Tokenization:
Tokenization is the process of breaking up text into words, keywords, phrases or other elements called tokens.
Tokens can be individual words, phrases or even whole sentences. 

#### Vectorization
Vectorization refers to encoding words or tokens as integers or floating point values for use as an input to a machine learning algorithm. 

I am goint to use the scikit-learn library to perform both tokenization and vectorization.

In [4]:
#%run data_exploration.ipynb
data_frame

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,Other,ACT I
1,2,Henry IV,NaN,NaN,Other,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,Other,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"
...,...,...,...,...,...,...
111391,111392,A Winters Tale,38.0,5.3.180,LEONTES,"Lead us from hence, where we may leisurely"
111392,111393,A Winters Tale,38.0,5.3.181,LEONTES,Each one demand an answer to his part
111393,111394,A Winters Tale,38.0,5.3.182,LEONTES,Perform'd in this wide gap of time since first
111394,111395,A Winters Tale,38.0,5.3.183,LEONTES,We were dissever'd: hastily lead away.
111395,111396,A Winters Tale,38.0,NaN,LEONTES,Exeunt

In [6]:
from sklearn.feature_extraction.text import TfidVectorizer
v=TfidVectorizer
x=v.fit_transform(data_frame['PlayerLine'])

ImportError: cannot import name 'TfidVectorizer' from 'sklearn.feature_extraction.text' (/home/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py)